// <auto-generated />
namespace SuperSimpleBlog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ReasonableBlogProps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReasonableBlogProps));
        
        string IMigrationMetadata.Id
        {
            get { return "201404031426154_ReasonableBlogProps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
